### ISSUE TITLE
Support extensionless file

### ISSUE THREAD

**Issue by kuon** [elixir-lang/mime#18]
I added

```
config :mime, :types, %{
  "application/json" => ["apple-app-site-association"]
}
```

to my app config, but, `from_path/1` do not return the proper type:

```
iex(1)> MIME.from_path("apple-app-site-association")
"application/octet-stream"
iex(2)> MIME.type("apple-app-site-association")     
"application/json"
```

It looks like it is because you default to the default type is the file has no extension.

**Comment by josevalim** [comment]
That's not going to work as you expect. You are effectively replacing the .json format by "apple-app-side-association". I am assuming you have this file at static and you want to serve it as JSON. The best option here is to allow a configuration on Plug.Static but I believe regardless of the format, whatever is fetching this file will consider it to be JSON anyway?

**Comment by kuon** [comment]
Yes, I'd like this to be served as json with Plug.Static. While iOS don't complain with default mime type, I'd like this to be setup properly (there are so many thing that could involved, CDN, cloudflare...), you never now how this could bite you.

**Comment by josevalim** [comment]
Fair enough. Through Plug.Static is the way to go then.
